FROM tiangolo/uwsgi-nginx-flask:python3.7

LABEL maintainer="Aaron Xu <aaron.xu.com>"

COPY requirements.txt /requirements.txt

RUN sed -i 's/deb.debian.org/mirror.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirror.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y apt-utils && \
    apt-get install -y \
    g++ \
    libssl-dev libffi-dev liblzma-dev xz-utils zlib1g-dev libc6-dev libjpeg-dev libpng-dev \
    libpcre3 libpcre3-dev tk-dev tcl-dev && \
    pip3 install --upgrade pip  --no-cache-dir -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
    pip3 install --no-cache-dir -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -r /requirements.txt && \
    rm -rf /root/.cache /tmp/*

COPY ./app /app