FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.8

LABEL maintainer="Aaron Xu <aaron.xu.com>"

COPY requirements.txt /requirements.txt

RUN sed -i 's/dl-cdn.alpinelinux.org/mirror.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
    apk add --no-cache --virtual=build-dependencies \
    g++ \
    build-base libffi-dev python3-dev \
    libffi openssl ca-certificates \
    jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \
    linux-headers pcre-dev  && \
    pip3 install --upgrade pip  --no-cache-dir -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
    pip3 install --no-cache-dir -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -r /requirements.txt && \
    apk del g++ && \
    # apk del --purge build-dependencies && \
    echo "py-autoreload = 1" >> /etc/uwsgi/uwsgi.ini && \
    rm -rf /root/.cache /tmp/*

COPY ./app /app